# Generated by Django 2.2.6 on 2019-10-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_image', models.ImageField(default='allImage/default.jpg', upload_to='allImage/')),
                ('image_name', models.CharField(max_length=60)),
                ('image_description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygallery.ImageCategory')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygallery.ImageLocation')),
            ],
        ),
    ]
