# Generated by Django 2.2.6 on 2019-10-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0002_auto_20191004_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='imagelocation',
            old_name='location_name',
            new_name='name',
        ),
    ]
