# Generated by Django 2.2.6 on 2019-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0003_auto_20191004_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='my_image',
            field=models.ImageField(default='album/default.jpg', upload_to='album/'),
        ),
    ]
